eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: PRODUCTSERVICE
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/products/**

        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payments/**

        - id: ORDERSERVICE
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/orders/**

        - id: INVENTORYSERVICE
          uri: lb://INVENTORYSERVICE
          predicates:
            - Path=/inventory/**

okta:
  oauth2:
    issuer: https://trial-5285711.okta.com/oauth2/default
    audience: api://default
    client-id: 0oayhs9h6rxSq5l3f697
    client-secret: k7JwjDW9RkVuSF_z3Ld6OyDnQfByXbwCEhXCQoU3Mj_5hENYYcACRSfcMcM1JwkI
    scopes: openid, profile, email, offline_access

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    filter: true
    default-models-expand-depth: -1
    syntax-highlight:
      theme: obsidian